[env]
TERM = "xterm-256color"

[shell]
program = "zellij"

[window]
dimensions = { columns = 140, lines = 45 }
padding.x = 16
padding.y = 14
#decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
